Error: React Hook "usePlasmicQueryData" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
Need to figure out why this is loaded many times with router as null